### ISSUE TITLE
Cannot item upgrade with Block Crystals

### ISSUE THREAD

**Issue by prismaticsoul** [CookieMonsterDev/titans-league#44]
**Description**:

Cannot item upgrade with Block Crystals

**Current behaviour**:

Clicking on Titan Shield within the Item Upgrade window, then clicking on Upgrade Block fails, giving a "Something went wrong, please try again" message in chat window.

**Expected behaviour**:

When clicking on Upgrade Block, there should be an option to spend Block Crystal to improve block on shields.

**Steps to reproduce the problem**:

Click Item Upgrader.
Select your shield.
Click Upgrade Block.

**Comment by VincentVanclef** [comment]
https://i.imgur.com/vAgz95Z.png

I can add both block and block rating o.0 @Cillez @CookieMonsterDev can you reproduce this?

**Comment by Neverlight-Jyria** [comment]
I'm able to add block rating fine since its a different stat than Block itself. But i do get the same error when trying to upgrade the block stat itself

**Comment by VincentVanclef** [comment]
Alright that should be fixed in the next core release, found that one.

**Comment by 161732** [comment]
I'm still getting the same error after the update. I have Wall Shield magnetized to it, 10 levels in armor, no other upgrades. Tried swapping magnetic, unequip & reequip.
